### ISSUE TITLE
This library use MDetect without proper attribution

### ISSUE THREAD

**Issue by dev-myatminsoe** [agpyaephyo/agpyaephyo.github.io#1]
I found that this library use https://github.com/myatmins/MDetect without License and copyright notice

**Comment by agpyaephyo** [comment]
I didn't saw this issue you logged. This page is not being maintained for very long time. I only saw the issue from the sample-code repo. Thought you were joking. That's why I replied your issue from sample-code repo with a half-joke. 

It is never my intention to make it look like I implement without using any existing code or idea. And I never promote myself attaching with this library. I don't even mention it as my library in my classes.

I just got super mad when I see you trash the PADC name on Facebook last night. Anyway, it is my bad that I forgot to mention you & rabbit repo on this Read-Me. I will update the page.
